basic:
    name: Syngenta
    environments:
        production: 'https://cp-product.syngenta.co.jp/'
        staging: 'https://syngentajpcpstg.prod.acquia-sites.com/'
        development: ''
    breakpoints:
        - 375
        - 1240
    pages:
        - product/kiwamipz_wp
        - product/amistar_20sc
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 10
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
